pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/your_username/your_project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t your_dockerhub_username/my-django-app .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker push your_dockerhub_username/my-django-app'
                }
            }
        }
    }
}
