pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/SRCEM-AIM-Class-A/A50_Himanshu_Kanjwani_Django_App.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t himanshuk713/my-django-app .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker push himanshuk713/my-django-app'
                }
            }
        }
    }
}
